### ISSUE TITLE
Implement first API

### ISSUE THREAD

**Issue by Thesola10** [Thesola10/PictoChat#3]
This is the main issue tracking development on the PCPA library. By the time this issue is fixed, at least the PictoChat sniffer and spoofer should be able to work, even if on one channel only.

### Requirements:
 - [ ] Buy a Prism54 WiFi adapter (#1)
 - [ ] Test and clean up PictoSniff code (#2)
 - [ ] Reverse-engineer PictoChat message generation
 - [ ] Send a PictoChat to a real Nintendo DS
 - [ ] Document everything so far using Doxygen
### Extra objectives:
 - [ ] Reverse-engineer all four PictoChat channels
 - [ ] Successfully send and receive messages on all four channels
 - [ ] Base the library on ESP32 (#5)

This issue will not be worked on until #2 is closed.
